### ISSUE TITLE
Put

### ISSUE THREAD

**Issue by alfredudu** [univas/php-todolist#1]
Edy,

Acredito que o put esteja com algum problema, ele retorna a mensagem de sucesso mas não grava no banco a atualização.

**Comment by edysegura** [comment]
Hi Alfredo! Thank you very much for reporting this issue! I've fix it in this [commit](https://github.com/univas/php-todolist/commit/4779b4c2d4974cd95dee0883b9c4255393377fc1).

Please check that again and let me know if it works!
